name: UV Python Versions

on:
  workflow_dispatch:

jobs:
  list-python:
    runs-on: macos-15
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Python 3.13 versions
        run: uv python list --all-versions 3.13

      - name: Python 3.14 versions
        run: uv python list --all-versions 3.14

      - name: test Python 3.13.8
        run: uv python install 3.13.8
